//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleLMS.EF_Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documents()
        {
            this.AspNetUsers = new HashSet<AspNetUsers>();
            this.Courses = new HashSet<Courses>();
            this.Activities = new HashSet<Activities>();
            this.Modules = new HashSet<Modules>();
        }
    
        public int Id { get; set; }
        public int DocumentTypeId { get; set; }
        public int ReceiverTypeId { get; set; }
        public string DocumentName { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public string UploadedByName { get; set; }
        public string UploadedByUserId { get; set; }
        public System.DateTime TimeOfRegistration { get; set; }
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
    
        public virtual DocumentTypes DocumentTypes { get; set; }
        public virtual ReceiverTypes ReceiverTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Courses> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Modules> Modules { get; set; }
    }
}
